#!/bin/bash

ruta_ejecucion=$(dirname "$(readlink -f "$0")") #es la ruta de ejecucion del script sin la / al final
ruta_escritorio=$(xdg-user-dir DESKTOP) #es la ruta de tu escritorio sin la / al final

#colores
rojo="\e[0;31m\033[1m" #rojo
verde="\e[;32m\033[1m"
azul="\e[0;34m\033[1m"
amarillo="\e[0;33m\033[1m"
rosa="\e[0;35m\033[1m"
turquesa="\e[0;36m\033[1m"
borra_colores="\033[0m\e[0m" #borra colores

# Función para validar una dirección IP
validate_ip() {
local ip=$1
local valid_ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

if [[ $ip =~ $valid_ip_regex ]]; then
    ip_correpto="si"
else
    echo -e "${amarillo} Error: Dirección IP no válida.${borra_colores}"
    ip_correpto="no"
fi
}

# Función para validar un nombre sin caracteres especiales ni en blanco
validate_name() {
local name=$1
local valid_name_regex="^[a-zA-Z0-9_]+$"

if [[ $name =~ $valid_name_regex && ! -z $name ]]; then
    nombre_correpto="si"
else
    echo -e "${amarillo} Error: Nombre no válido. Debe contener solo letras, números y guiones bajos, y no puede estar en blanco.${borra_colores}"
    nombre_correpto="no"
fi
}



# Buscar la cadena "declare -A ips" en el archivo
            if ! grep -q 'declare -A ips' "$ruta_ejecucion/MonitorRedIps.config"; then
                echo "declare -A ips" >> $ruta_ejecucion/MonitorRedIps.config
            fi


            while true
            do
                clear
                echo ""
                echo -e "${azul}- Listado de tus IPS para saber si estan activas. -${borra_colores}"
                echo ""
                tail -n +2 $ruta_ejecucion/MonitorRedIps.config 2>/dev/null | awk -F'[[\\]=]+' '{print "\033[32m" $3 "\033[0m =", "\033[32m" $2 "\033[0m"}' | column -t; echo ""
                echo ""

                # Solicitar y validar la dirección IP
                echo -e "${amarillo} Ej. router 192.168.1.1 (S -> Terminar de introducir datos.).${borra_colores}"
                read -p " Dime un Nombre Dispositivo espacio y su dirección IP -> " name ip
                echo ""
                if  [ "$name" == "s" ] || [ "$name" == "S" ]; then
                    # Comprobar si el archivo contiene el carácter "="
                    if grep -q "=" "$ruta_ejecucion/MonitorRedIps.config"; then
                        sed -i 's/configurado_ips="no"/configurado_ips="si"/' $ruta_ejecucion/configurado.config
                        break
                    else
                        echo -e "${amarillo} No has introducido ninguna Ip${borra_colores}"; sleep 3
                        break
                    fi
                fi

                validate_ip "$ip"
                validate_name "$name"

                # Verifica si se debe salir del bucle


                # Agrega la entrada al archivo como un nuevo elemento del array
                if [[ "$ip_correpto" == "si" ]] && [[ "$nombre_correpto" == "si" ]]; then
                    echo "ips[$ip]=$name" >> $ruta_ejecucion/MonitorRedIps.config
                    echo ""
                    echo -e " Dispositivo ${azul}$name${borra_colores} con la ${azul}$ip${borra_colores} = ${verde}ok${borra_colores}."
                    sleep 2
                else
                    echo -e "${rojo} Datos de dispositivo incorreptos.${borra_colores}"
                    echo ""
                    read -p " Pulsa una tecla para continuar." p
                fi
            done


